/* C code for program sncExample2, generated by snc from ../sncExample2.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
struct seqg_vars {
# line 3 "../sncExample2.stt"
	int linac_count;
# line 4 "../sncExample2.stt"
	int ringhall_count;
# line 5 "../sncExample2.stt"
	int ringcenter_count;
# line 16 "../sncExample2.stt"
	int i;
# line 16 "../sncExample2.stt"
	int j;
# line 18 "../sncExample2.stt"
	epicsInt32 linac_in[4];
# line 24 "../sncExample2.stt"
	epicsInt32 linac_in_temp[4];
# line 26 "../sncExample2.stt"
	epicsInt32 linac_out[4];
# line 32 "../sncExample2.stt"
	epicsInt32 linac_out_temp[4];
# line 34 "../sncExample2.stt"
	epicsInt32 ring_in[10];
# line 46 "../sncExample2.stt"
	epicsInt32 ring_in_temp[8];
# line 49 "../sncExample2.stt"
	epicsInt32 ring_out[10];
# line 61 "../sncExample2.stt"
	epicsInt32 ring_out_temp[8];
# line 70 "../sncExample2.stt"
	int doorstate_linac_in[4];
# line 77 "../sncExample2.stt"
	int doorstate_linac_out[4];
# line 86 "../sncExample2.stt"
	int doorstate_ring_in[10];
# line 98 "../sncExample2.stt"
	int doorstate_ring_out[10];
# line 113 "../sncExample2.stt"
	int cyclereset_snl_2;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 24 "../sncExample2.stt"
	static epicsInt32 seqg_initvar_linac_in_temp[4] = {0, 0, 0, 0};
	memcpy(&seqg_var->linac_in_temp, &seqg_initvar_linac_in_temp, sizeof(seqg_initvar_linac_in_temp));
	}
	{
# line 32 "../sncExample2.stt"
	static epicsInt32 seqg_initvar_linac_out_temp[4] = {0, 0, 0, 0};
	memcpy(&seqg_var->linac_out_temp, &seqg_initvar_linac_out_temp, sizeof(seqg_initvar_linac_out_temp));
	}
	{
# line 46 "../sncExample2.stt"
	static epicsInt32 seqg_initvar_ring_in_temp[8] = {0, 0, 0, 0, 0, 0, 0, 0};
	memcpy(&seqg_var->ring_in_temp, &seqg_initvar_ring_in_temp, sizeof(seqg_initvar_ring_in_temp));
	}
	{
# line 61 "../sncExample2.stt"
	static epicsInt32 seqg_initvar_ring_out_temp[8] = {0, 0, 0, 0, 0, 0, 0, 0};
	memcpy(&seqg_var->ring_out_temp, &seqg_initvar_ring_out_temp, sizeof(seqg_initvar_ring_out_temp));
	}
}

/****** Code for state "init" in state set "ss1" ******/

/* Event function for state "init" in state set "ss1" */
static seqBool seqg_event_ss1_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 121 "../sncExample2.stt"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ss1" */
static void seqg_action_ss1_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 122 "../sncExample2.stt"
			seqg_var->linac_count = 0;
# line 123 "../sncExample2.stt"
			seqg_var->ringhall_count = 0;
# line 124 "../sncExample2.stt"
			seqg_var->ringcenter_count = 0;
# line 125 "../sncExample2.stt"
			seq_pvPutTmo(seqg_env, 0/*linac_count*/, DEFAULT, DEFAULT_TIMEOUT);
# line 126 "../sncExample2.stt"
			seq_pvPutTmo(seqg_env, 1/*ringhall_count*/, DEFAULT, DEFAULT_TIMEOUT);
# line 127 "../sncExample2.stt"
			seq_pvPutTmo(seqg_env, 2/*ringcenter_count*/, DEFAULT, DEFAULT_TIMEOUT);
# line 128 "../sncExample2.stt"
			printf("Test22222 Start.\n\n\n\n");
# line 130 "../sncExample2.stt"
			for (seqg_var->i = 0; seqg_var->i <= 3; seqg_var->i++)
			{
# line 131 "../sncExample2.stt"
				seqg_var->doorstate_linac_in[seqg_var->i] = 0;
# line 132 "../sncExample2.stt"
				seqg_var->doorstate_linac_out[seqg_var->i] = 0;
# line 133 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 31/*doorstate_linac_in*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 134 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 35/*doorstate_linac_out*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
			}
# line 137 "../sncExample2.stt"
			for (seqg_var->j = 0; seqg_var->j <= 9; seqg_var->j++)
			{
# line 138 "../sncExample2.stt"
				seqg_var->doorstate_ring_in[seqg_var->j] = 0;
# line 139 "../sncExample2.stt"
				seqg_var->doorstate_ring_out[seqg_var->j] = 0;
# line 140 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 39/*doorstate_ring_in*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
# line 141 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 49/*doorstate_ring_out*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "count" in state set "ss1" ******/

/* Event function for state "count" in state set "ss1" */
static seqBool seqg_event_ss1_0_count(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 148 "../sncExample2.stt"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "count" in state set "ss1" */
static void seqg_action_ss1_0_count(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 149 "../sncExample2.stt"
			for (seqg_var->i = 0; seqg_var->i <= 1; seqg_var->i++)
			{
# line 150 "../sncExample2.stt"
				if ((seqg_var->linac_in[seqg_var->i] != seqg_var->linac_in_temp[seqg_var->i]) && (seqg_var->linac_in[seqg_var->i] != 0))
				{
# line 151 "../sncExample2.stt"
					seqg_var->linac_count++;
# line 152 "../sncExample2.stt"
					seqg_var->linac_in_temp[seqg_var->i] = seqg_var->linac_in[seqg_var->i];
# line 153 "../sncExample2.stt"
					seqg_var->doorstate_linac_in[seqg_var->i] = 1;
# line 154 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 31/*doorstate_linac_in*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 155 "../sncExample2.stt"
					printf("Cardnumber: %Id entering LINAC\n.", seqg_var->linac_in[seqg_var->i]);
# line 156 "../sncExample2.stt"
					printf("PERSONNEL NUMBER in LINAC is:  %d\n\n", seqg_var->linac_count);
# line 157 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 0/*linac_count*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 161 "../sncExample2.stt"
				if ((seqg_var->linac_out[seqg_var->i] != seqg_var->linac_out_temp[seqg_var->i]) && (seqg_var->linac_out[seqg_var->i] != 0))
				{
# line 162 "../sncExample2.stt"
					seqg_var->linac_count--;
# line 163 "../sncExample2.stt"
					seqg_var->linac_out_temp[seqg_var->i] = seqg_var->linac_out[seqg_var->i];
# line 164 "../sncExample2.stt"
					seqg_var->doorstate_linac_out[seqg_var->i] = 1;
# line 165 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 35/*doorstate_linac_out*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 166 "../sncExample2.stt"
					printf("Cardnumber: %Id lefting LINAC\n", seqg_var->linac_out[seqg_var->i]);
# line 167 "../sncExample2.stt"
					printf("PERSONNEL NUMBER in LINAC is: %d\n\n", seqg_var->linac_count);
# line 168 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 0/*linac_count*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 175 "../sncExample2.stt"
			for (seqg_var->j = 0; seqg_var->j <= 6; seqg_var->j++)
			{
# line 176 "../sncExample2.stt"
				if ((seqg_var->ring_in[seqg_var->j] != seqg_var->ring_in_temp[seqg_var->j]) && (seqg_var->ring_in[seqg_var->j] != 0))
				{
# line 177 "../sncExample2.stt"
					seqg_var->ringhall_count++;
# line 178 "../sncExample2.stt"
					seqg_var->ring_in_temp[seqg_var->j] = seqg_var->ring_in[seqg_var->j];
# line 179 "../sncExample2.stt"
					seqg_var->doorstate_ring_in[seqg_var->j] = 1;
# line 180 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 39/*doorstate_ring_in*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
# line 181 "../sncExample2.stt"
					printf("Cardnumber: %Id entering RING HALL\n", seqg_var->ring_in[seqg_var->j]);
# line 182 "../sncExample2.stt"
					printf("PERSONNEL NUMBER in RING HALL is: %d\n\n", seqg_var->ringhall_count);
# line 183 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 1/*ringhall_count*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 186 "../sncExample2.stt"
				if ((seqg_var->ring_out[seqg_var->j] != seqg_var->ring_out_temp[seqg_var->j]) && (seqg_var->ring_out[seqg_var->j] != 0))
				{
# line 187 "../sncExample2.stt"
					seqg_var->ringhall_count--;
# line 188 "../sncExample2.stt"
					seqg_var->ring_out_temp[seqg_var->j] = seqg_var->ring_out[seqg_var->j];
# line 189 "../sncExample2.stt"
					seqg_var->doorstate_ring_out[seqg_var->j] = 1;
# line 190 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 49/*doorstate_ring_out*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
# line 191 "../sncExample2.stt"
					printf("Cardnumber: %Id lefting RING HALL\n", seqg_var->ring_out[seqg_var->j]);
# line 192 "../sncExample2.stt"
					printf("PERSONNEL NUMBER in RING HALL is: %d\n\n", seqg_var->ringhall_count);
# line 193 "../sncExample2.stt"
					seq_pvPutTmo(seqg_env, 1/*ringhall_count*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 197 "../sncExample2.stt"
			if ((seqg_var->ring_out[9] != seqg_var->ring_out_temp[7]) && (seqg_var->ring_out[9] != 0))
			{
# line 198 "../sncExample2.stt"
				seqg_var->ringhall_count--;
# line 199 "../sncExample2.stt"
				seqg_var->ringcenter_count++;
# line 200 "../sncExample2.stt"
				seqg_var->ring_out_temp[7] = seqg_var->ring_out[9];
# line 201 "../sncExample2.stt"
				seqg_var->doorstate_ring_out[9] = 1;
# line 202 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 49/*doorstate_ring_out*/ + (CH_ID)(9), DEFAULT, DEFAULT_TIMEOUT);
# line 203 "../sncExample2.stt"
				printf("Cardnumber: %Id entering RING CENTER\n", seqg_var->ring_out[9]);
# line 204 "../sncExample2.stt"
				printf("PERSONNEL NUMBER in RING CENTER is: %d\n", seqg_var->ringcenter_count);
# line 205 "../sncExample2.stt"
				printf("PERSONNEL NUMBER in RING HALL is: %d\n\n", seqg_var->ringhall_count);
# line 206 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 2/*ringcenter_count*/, DEFAULT, DEFAULT_TIMEOUT);
# line 207 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 1/*ringhall_count*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 210 "../sncExample2.stt"
			if ((seqg_var->ring_in[9] != seqg_var->ring_in_temp[7]) && (seqg_var->ring_in[9] != 0))
			{
# line 211 "../sncExample2.stt"
				seqg_var->ringhall_count++;
# line 212 "../sncExample2.stt"
				seqg_var->ringcenter_count--;
# line 214 "../sncExample2.stt"
				seqg_var->ring_in_temp[7] = seqg_var->ring_in[9];
# line 215 "../sncExample2.stt"
				seqg_var->doorstate_ring_in[9] = 1;
# line 216 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 39/*doorstate_ring_in*/ + (CH_ID)(9), DEFAULT, DEFAULT_TIMEOUT);
# line 217 "../sncExample2.stt"
				printf("Cardnumber: %Id lefting RING CENTER\n", seqg_var->ring_in[9]);
# line 218 "../sncExample2.stt"
				printf("PERSONNEL NUMBER in RING CENTER is: %d\n", seqg_var->ringcenter_count);
# line 219 "../sncExample2.stt"
				printf("PERSONNEL NUMBER in RING HALL is: %d\n\n", seqg_var->ringhall_count);
# line 220 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 2/*ringcenter_count*/, DEFAULT, DEFAULT_TIMEOUT);
# line 221 "../sncExample2.stt"
				seq_pvPutTmo(seqg_env, 1/*ringhall_count*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "delay" in state set "ss1" ******/

/* Event function for state "delay" in state set "ss1" */
static seqBool seqg_event_ss1_0_delay(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 229 "../sncExample2.stt"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "delay" in state set "ss1" */
static void seqg_action_ss1_0_delay(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 230 "../sncExample2.stt"
			if (seqg_var->cyclereset_snl_2 == 1)
			{
# line 231 "../sncExample2.stt"
				for (seqg_var->i = 0; seqg_var->i <= 3; seqg_var->i++)
				{
# line 232 "../sncExample2.stt"
					seqg_var->linac_in_temp[seqg_var->i] = 0;
# line 233 "../sncExample2.stt"
					seqg_var->linac_out_temp[seqg_var->i] = 0;
				}
# line 236 "../sncExample2.stt"
				for (seqg_var->j = 0; seqg_var->j <= 7; seqg_var->j++)
				{
# line 237 "../sncExample2.stt"
					seqg_var->ring_in_temp[seqg_var->j] = 0;
# line 238 "../sncExample2.stt"
					seqg_var->ring_out_temp[seqg_var->j] = 0;
				}
			}
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"HLS:PSS:LINAC:personnelCount:Cacl", offsetof(struct seqg_vars, linac_count), "linac_count", P_INT, 1, 1, 0, 1, 0, 0},
	{"HLS:PSS:RINGHALL:personnelCount:Cacl", offsetof(struct seqg_vars, ringhall_count), "ringhall_count", P_INT, 1, 2, 0, 1, 0, 0},
	{"HLS:PSS:RINGCENTER:personnelCount:Cacl", offsetof(struct seqg_vars, ringcenter_count), "ringcenter_count", P_INT, 1, 3, 0, 1, 0, 0},
	{"HLS:PSS:door10:cardreader:in:longin", offsetof(struct seqg_vars, linac_in[0]), "linac_in[0]", P_INT32T, 1, 4, 0, 1, 0, 0},
	{"HLS:PSS:door11:cardreader:in:longin", offsetof(struct seqg_vars, linac_in[1]), "linac_in[1]", P_INT32T, 1, 5, 0, 1, 0, 0},
	{"HLS:PSS:door13:cardreader:in:longin", offsetof(struct seqg_vars, linac_in[2]), "linac_in[2]", P_INT32T, 1, 6, 0, 1, 0, 0},
	{"HLS:PSS:door14:cardreader:in:longin", offsetof(struct seqg_vars, linac_in[3]), "linac_in[3]", P_INT32T, 1, 7, 0, 1, 0, 0},
	{"HLS:PSS:door10:cardreader:out:longin", offsetof(struct seqg_vars, linac_out[0]), "linac_out[0]", P_INT32T, 1, 8, 0, 1, 0, 0},
	{"HLS:PSS:door11:cardreader:out:longin", offsetof(struct seqg_vars, linac_out[1]), "linac_out[1]", P_INT32T, 1, 9, 0, 1, 0, 0},
	{"HLS:PSS:door13:cardreader:out:longin", offsetof(struct seqg_vars, linac_out[2]), "linac_out[2]", P_INT32T, 1, 10, 0, 1, 0, 0},
	{"HLS:PSS:door14:cardreader:out:longin", offsetof(struct seqg_vars, linac_out[3]), "linac_out[3]", P_INT32T, 1, 11, 0, 1, 0, 0},
	{"HLS:PSS:door01:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[0]), "ring_in[0]", P_INT32T, 1, 12, 0, 1, 0, 0},
	{"HLS:PSS:door02:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[1]), "ring_in[1]", P_INT32T, 1, 13, 0, 1, 0, 0},
	{"HLS:PSS:door03:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[2]), "ring_in[2]", P_INT32T, 1, 14, 0, 1, 0, 0},
	{"HLS:PSS:door04:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[3]), "ring_in[3]", P_INT32T, 1, 15, 0, 1, 0, 0},
	{"HLS:PSS:door05:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[4]), "ring_in[4]", P_INT32T, 1, 16, 0, 1, 0, 0},
	{"HLS:PSS:door06:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[5]), "ring_in[5]", P_INT32T, 1, 17, 0, 1, 0, 0},
	{"HLS:PSS:door07:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[6]), "ring_in[6]", P_INT32T, 1, 18, 0, 1, 0, 0},
	{"HLS:PSS:door08:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[7]), "ring_in[7]", P_INT32T, 1, 19, 0, 1, 0, 0},
	{"HLS:PSS:door09:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[8]), "ring_in[8]", P_INT32T, 1, 20, 0, 1, 0, 0},
	{"HLS:PSS:door12:cardreader:in:longin", offsetof(struct seqg_vars, ring_in[9]), "ring_in[9]", P_INT32T, 1, 21, 0, 1, 0, 0},
	{"HLS:PSS:door01:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[0]), "ring_out[0]", P_INT32T, 1, 22, 0, 1, 0, 0},
	{"HLS:PSS:door02:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[1]), "ring_out[1]", P_INT32T, 1, 23, 0, 1, 0, 0},
	{"HLS:PSS:door03:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[2]), "ring_out[2]", P_INT32T, 1, 24, 0, 1, 0, 0},
	{"HLS:PSS:door04:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[3]), "ring_out[3]", P_INT32T, 1, 25, 0, 1, 0, 0},
	{"HLS:PSS:door05:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[4]), "ring_out[4]", P_INT32T, 1, 26, 0, 1, 0, 0},
	{"HLS:PSS:door06:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[5]), "ring_out[5]", P_INT32T, 1, 27, 0, 1, 0, 0},
	{"HLS:PSS:door07:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[6]), "ring_out[6]", P_INT32T, 1, 28, 0, 1, 0, 0},
	{"HLS:PSS:door08:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[7]), "ring_out[7]", P_INT32T, 1, 29, 0, 1, 0, 0},
	{"HLS:PSS:door09:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[8]), "ring_out[8]", P_INT32T, 1, 30, 0, 1, 0, 0},
	{"HLS:PSS:door12:cardreader:out:longin", offsetof(struct seqg_vars, ring_out[9]), "ring_out[9]", P_INT32T, 1, 31, 0, 1, 0, 0},
	{"HLS:PSS:door10:state:in:bo", offsetof(struct seqg_vars, doorstate_linac_in[0]), "doorstate_linac_in[0]", P_INT, 1, 32, 0, 1, 0, 0},
	{"HLS:PSS:door11:state:in:bo", offsetof(struct seqg_vars, doorstate_linac_in[1]), "doorstate_linac_in[1]", P_INT, 1, 33, 0, 1, 0, 0},
	{"HLS:PSS:door13:state:in:bo", offsetof(struct seqg_vars, doorstate_linac_in[2]), "doorstate_linac_in[2]", P_INT, 1, 34, 0, 1, 0, 0},
	{"HLS:PSS:door14:state:in:bo", offsetof(struct seqg_vars, doorstate_linac_in[3]), "doorstate_linac_in[3]", P_INT, 1, 35, 0, 1, 0, 0},
	{"HLS:PSS:door10:state:out:bo", offsetof(struct seqg_vars, doorstate_linac_out[0]), "doorstate_linac_out[0]", P_INT, 1, 36, 0, 1, 0, 0},
	{"HLS:PSS:door11:state:out:bo", offsetof(struct seqg_vars, doorstate_linac_out[1]), "doorstate_linac_out[1]", P_INT, 1, 37, 0, 1, 0, 0},
	{"HLS:PSS:door13:state:out:bo", offsetof(struct seqg_vars, doorstate_linac_out[2]), "doorstate_linac_out[2]", P_INT, 1, 38, 0, 1, 0, 0},
	{"HLS:PSS:door14:state:out:bo", offsetof(struct seqg_vars, doorstate_linac_out[3]), "doorstate_linac_out[3]", P_INT, 1, 39, 0, 1, 0, 0},
	{"HLS:PSS:door01:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[0]), "doorstate_ring_in[0]", P_INT, 1, 40, 0, 1, 0, 0},
	{"HLS:PSS:door02:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[1]), "doorstate_ring_in[1]", P_INT, 1, 41, 0, 1, 0, 0},
	{"HLS:PSS:door03:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[2]), "doorstate_ring_in[2]", P_INT, 1, 42, 0, 1, 0, 0},
	{"HLS:PSS:door04:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[3]), "doorstate_ring_in[3]", P_INT, 1, 43, 0, 1, 0, 0},
	{"HLS:PSS:door05:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[4]), "doorstate_ring_in[4]", P_INT, 1, 44, 0, 1, 0, 0},
	{"HLS:PSS:door06:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[5]), "doorstate_ring_in[5]", P_INT, 1, 45, 0, 1, 0, 0},
	{"HLS:PSS:door07:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[6]), "doorstate_ring_in[6]", P_INT, 1, 46, 0, 1, 0, 0},
	{"HLS:PSS:door08:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[7]), "doorstate_ring_in[7]", P_INT, 1, 47, 0, 1, 0, 0},
	{"HLS:PSS:door09:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[8]), "doorstate_ring_in[8]", P_INT, 1, 48, 0, 1, 0, 0},
	{"HLS:PSS:door12:state:in:bo", offsetof(struct seqg_vars, doorstate_ring_in[9]), "doorstate_ring_in[9]", P_INT, 1, 49, 0, 1, 0, 0},
	{"HLS:PSS:door01:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[0]), "doorstate_ring_out[0]", P_INT, 1, 50, 0, 1, 0, 0},
	{"HLS:PSS:door02:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[1]), "doorstate_ring_out[1]", P_INT, 1, 51, 0, 1, 0, 0},
	{"HLS:PSS:door03:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[2]), "doorstate_ring_out[2]", P_INT, 1, 52, 0, 1, 0, 0},
	{"HLS:PSS:door04:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[3]), "doorstate_ring_out[3]", P_INT, 1, 53, 0, 1, 0, 0},
	{"HLS:PSS:door05:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[4]), "doorstate_ring_out[4]", P_INT, 1, 54, 0, 1, 0, 0},
	{"HLS:PSS:door06:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[5]), "doorstate_ring_out[5]", P_INT, 1, 55, 0, 1, 0, 0},
	{"HLS:PSS:door07:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[6]), "doorstate_ring_out[6]", P_INT, 1, 56, 0, 1, 0, 0},
	{"HLS:PSS:door08:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[7]), "doorstate_ring_out[7]", P_INT, 1, 57, 0, 1, 0, 0},
	{"HLS:PSS:door09:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[8]), "doorstate_ring_out[8]", P_INT, 1, 58, 0, 1, 0, 0},
	{"HLS:PSS:door12:state:out:bo", offsetof(struct seqg_vars, doorstate_ring_out[9]), "doorstate_ring_out[9]", P_INT, 1, 59, 0, 1, 0, 0},
	{"cyclereset:ai", offsetof(struct seqg_vars, cyclereset_snl_2), "cyclereset_snl_2", P_INT, 1, 60, 0, 1, 0, 0},
};

/* Event masks for state set "ss1" */
static const seqMask seqg_mask_ss1_0_init[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_count[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_delay[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "ss1" */
static seqState seqg_states_ss1[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ss1_0_init,
	/* event function */    seqg_event_ss1_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "count",
	/* action function */   seqg_action_ss1_0_count,
	/* event function */    seqg_event_ss1_0_count,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_count,
	/* state options */     (0)
	},
	{
	/* state name */        "delay",
	/* action function */   seqg_action_ss1_0_delay,
	/* event function */    seqg_event_ss1_0_delay,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_delay,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ss1",
	/* states */            seqg_states_ss1,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram sncExample2 = {
	/* magic number */      2002004,
	/* program name */      "sncExample2",
	/* channels */          seqg_chans,
	/* num. channels */     60,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sncExample2Registrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sncExample2);
}
epicsExportRegistrar(sncExample2Registrar);
