TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
#DB += example.db
#DB += dbExample1.db
#DB += dbExample2.db
#DB += dbSubExample.db
DB += PSS.db
#DB += user.substitutions
#DB += userHost.substitutions
DB += PSS.substitutions

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

